### ISSUE TITLE
[STRI 2] Contract execution ends with negative balances

### ISSUE THREAD

**Issue by C0x41lch0x41** [stellar/stellar-turrets#4]
### What version are you using?
0.0.0

### Scenario
Users are allowed to run contracts as long as they have a balance strictly greater than zero: https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/txFunctions/run.js#L63

### Why
The cost is subtracted from the balance after the function runs:  https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/txFunctions/run.js#L114-L122

### Recommendation
We could check for the balances to be greater than the configured `timeout` for AWS lambdas times the `RUNNING_DIVISOR`. This is the maximum amount of cost that could be subtracted from the user's balance.

**Comment by silence48** [comment]
This issue is addressed in the fix for STRI 1 The specific code fixes are outlined in https://github.com/stellar/stellar-turrets/issues/3#issuecomment-1028440027

**Comment by C0x41lch0x41** [comment]
This is patched here: https://github.com/stellar/stellar-turrets/pull/11 and merged into master here: https://github.com/stellar/stellar-turrets/commit/cf6de0e32adfd2e6f1ff73a8eaa8e8cce9de00de
