### ISSUE TITLE
[STRI 5] Controlled account cannot heal if Turret is down

### ISSUE THREAD

**Issue by C0x41lch0x41** [stellar/stellar-turrets#6]
### What version are you using?
0.0.0

### Scenario
If Turret is down, it is not possible to heal the controlled account.

### Why
https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/ctrlAccounts/heal.js#L111-L114
`removeSigner` will not exist in `incomingTurretKeys`

### Recommendation
We should remove the check for `removeSigner` being present in `incomingTurretKeys`

**Comment by silence48** [comment]
To resolve STRI 5 and 6, I have rewritten the heal function entirely, and included a variety of utility functions. in 8da4937

The new workflows are found in L173 to L271 of trust.js

https://github.com/stellar/stellar-turrets/blob/8da4937077a9916d777e62e3def05c0293c810be/wrangler/src/trust/trust.js#L173-L271

**Comment by C0x41lch0x41** [comment]
This is patched here: https://github.com/stellar/stellar-turrets/pull/11 and merged into master here: https://github.com/stellar/stellar-turrets/commit/cf6de0e32adfd2e6f1ff73a8eaa8e8cce9de00de
