### ISSUE TITLE
[STRI 6] Malicious turret can block controlled account healing

### ISSUE THREAD

**Issue by C0x41lch0x41** [stellar/stellar-turrets#7]
### What version are you using?
0.0.0

### Scenario
Request an honest turret to remove a malicious one from the set of trusted signers fails.

### Why
`removeTurret` is not filtered from `existingSigners`: https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/ctrlAccounts/heal.js#L31
So it is present in `existingSigners`: https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/ctrlAccounts/heal.js#L61-L65

A new signer must be trusted by all `incomingTurretsKeys`: https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/ctrlAccounts/heal.js#L131-L134

### Recommendation
We should remove `removeSigner` from `existingSigners`

**Comment by silence48** [comment]
To resolve STRI 5 and 6, I have rewritten the heal function entirely, and included a variety of utility functions. in 8da4937

The new workflows are found in L173 to L271 of trust.js

https://github.com/stellar/stellar-turrets/blob/8da4937077a9916d777e62e3def05c0293c810be/wrangler/src/trust/trust.js#L173-L271

**Comment by C0x41lch0x41** [comment]
This is patched here: https://github.com/stellar/stellar-turrets/pull/11 and merged into master here: https://github.com/stellar/stellar-turrets/commit/cf6de0e32adfd2e6f1ff73a8eaa8e8cce9de00de
