### ISSUE TITLE
[STRI 7] Transaction fails if contract returns invalid XDR

### ISSUE THREAD

**Issue by C0x41lch0x41** [stellar/stellar-turrets#8]
### What version are you using?
0.0.0

### Scenario
If contract returns invalid XDR the corresponding transaction will fail

### Why
There is no check of the XDR before building the Transaction
https://github.com/stellar/stellar-turrets/blob/a459bc930a6458deb1e187be509212112b4214e7/wrangler/src/txFunctions/run.js#L157

### Recommendation
Try/catch the code

**Comment by silence48** [comment]
Resolved with try catch as seen in 1bd56d2

**Comment by C0x41lch0x41** [comment]
This is patched here: https://github.com/stellar/stellar-turrets/pull/11 and merged into master here: https://github.com/stellar/stellar-turrets/commit/cf6de0e32adfd2e6f1ff73a8eaa8e8cce9de00de
